service: proveedores
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role: arn:aws:iam::664349461262:role/lambdaExecution
functions:
  api:
    handler: src/lambda.handler
    timeout: 30
    events:
      - httpApi:
          method: ANY
          path: '/api/{proxy+}'
  seveFileS3:
    handler: src/lambda.seveFileS3
    timeout: 30
    events:
      - httpApi:
          method: post
          path: '/service/{proxy+}'
custom:
  esbuild:
    bundle: true
    minify: true
  serverless-offline:
    httpPort: 4000
plugins:
  - serverless-esbuild
  - serverless-offline
