service: proveedores-api
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs20.x
  timeout: 30
  iam:
    role: arn:aws:iam::664349461262:role/lambdaExecution
functions:
  api:
    handler: src/api/index.handler
    events:
      - httpApi:
          method: ANY
          path: '/api/{proxy+}'
  services:
    handler: src/services/index.handler
    events:
      - httpApi:
          method: post
          path: '/service/{proxy+}'
custom:
  dotenv:
    path: .env.dev
  esbuild:
    bundle: true
    minify: true
  serverless-offline:
    httpPort: 4000
plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin
