openapi: 3.0.0
info:
  title: lambda-express-sequelize
  description: documentación lambda-express-sequelize
  version: 1.0.0
  servers:
    - http://localhost:4000
paths:
  /api/Employee:
    get:
      tags:
        - Employee
      parameters: []
      requestBody: null
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                example:
                  - uuid: 0af28551-5030-4894-9870-5bdf085dcdda
                    firstName: Employee first name
                    middleName: Employee middle name
                    surname: Employee surname
                    middleSurname: Employee middle surname
                    documentType: Emp
                    documentNumber: 269
                    birthdate: '2024-03-17'
                    isActive: true
                    creatorUser: Employee creator user
                    editorUser: Employee editor user
                  - uuid: a4b59786-beea-43a4-8c1a-500b5978ab49
                    firstName: Employee first name
                    middleName: Employee middle name
                    surname: Employee surname
                    middleSurname: Employee middle surname
                    documentType: Emp
                    documentNumber: 665
                    birthdate: '2024-03-17'
                    isActive: true
                    creatorUser: Employee creator user
                    editorUser: Employee editor user
                  - uuid: a7894342-5f08-4531-975c-862cba7eaf2f
                    firstName: Employee first name
                    middleName: Employee middle name
                    surname: Employee surname
                    middleSurname: Employee middle surname
                    documentType: Emp
                    documentNumber: 515
                    birthdate: '2024-03-17'
                    isActive: true
                    creatorUser: Employee creator user
                    editorUser: Employee editor user
    post:
      tags:
        - Employee
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              example: &ref_0
                uuid: 2f6b7f19-e387-47f0-ac86-baf4ca1dc3c4
                firstName: Employee first name
                middleName: Employee middle name
                surname: Employee surname
                middleSurname: Employee middle surname
                documentType: Emp
                documentNumber: 724
                birthdate: '2024-03-17'
                isActive: true
                creatorUser: Employee creator user
                editorUser: Employee editor user
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                example: *ref_0
  /api/Employee/{uuid}:
    put:
      tags:
        - Employee
      parameters:
        - name: uuid
          in: path
          type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              example: &ref_1
                uuid: a7894342-5f08-4531-975c-862cba7eaf2f
                firstName: Employee first name
                middleName: Employee middle name
                surname: Employee surname
                middleSurname: Employee middle surname
                documentType: Emp
                documentNumber: 73
                birthdate: '2024-03-17'
                isActive: true
                creatorUser: Employee creator user
                editorUser: Employee editor user
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                example: *ref_1
  /api/Employee/filter?uuid={uuid}:
    get:
      tags:
        - Employee
      parameters:
        - name: uuid
          in: path
          type: string
          required: false
      requestBody: null
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                example:
                  - uuid: a4b59786-beea-43a4-8c1a-500b5978ab49
                    firstName: Employee first name
                    middleName: Employee middle name
                    surname: Employee surname
                    middleSurname: Employee middle surname
                    documentType: Emp
                    documentNumber: 665
                    birthdate: '2024-03-17'
                    isActive: true
                    creatorUser: Employee creator user
                    editorUser: Employee editor user
  /api/Supplier:
    get:
      tags:
        - Supplier
      parameters: []
      requestBody: null
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                example:
                  - uuid: 2c88eb77-7730-4fbd-830a-48d06454fe20
                    name: Supplier name
                    description: Supplier description
                    nit: 501
                    isActive: true
                    creatorUser: Supplier creator user
                    editorUser: Supplier editor user
                  - uuid: 96382cc6-a473-4485-a3b8-1fb4eb377c46
                    name: Supplier name
                    description: Supplier description
                    nit: 996
                    isActive: true
                    creatorUser: Supplier creator user
                    editorUser: Supplier editor user
                  - uuid: b389d73c-1b49-4a26-8f94-7b3641d72c81
                    name: Supplier name
                    description: Supplier description
                    nit: 507
                    isActive: true
                    creatorUser: Supplier creator user
                    editorUser: Supplier editor user
    post:
      tags:
        - Supplier
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              example: &ref_2
                uuid: 629f9f80-d4f7-40bc-a0b1-99100a8268c8
                name: Supplier name
                description: Supplier description
                nit: 503
                isActive: true
                creatorUser: Supplier creator user
                editorUser: Supplier editor user
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                example: *ref_2
  /api/Supplier/{uuid}:
    put:
      tags:
        - Supplier
      parameters:
        - name: uuid
          in: path
          type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              example: &ref_3
                uuid: 96382cc6-a473-4485-a3b8-1fb4eb377c46
                name: Supplier name
                description: Supplier description
                nit: 73
                isActive: true
                creatorUser: Supplier creator user
                editorUser: Supplier editor user
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                example: *ref_3
  /api/Supplier/filter?uuid={uuid}:
    get:
      tags:
        - Supplier
      parameters:
        - name: uuid
          in: path
          type: string
          required: false
      requestBody: null
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                example:
                  - uuid: b389d73c-1b49-4a26-8f94-7b3641d72c81
                    name: Supplier name
                    description: Supplier description
                    nit: 507
                    isActive: true
                    creatorUser: Supplier creator user
                    editorUser: Supplier editor user
components:
  parameters: {}
  definitions: {}
  schemas:
    Supplier:
      type: object
      properties:
        uuid:
          type: string
          required: true
          description: Identificador universal unico para la tabal proveedor.
          example: 629f9f80-d4f7-40bc-a0b1-99100a8268c8
        name:
          type: string
          required: true
          description: Nombre del proveedor.
          example: Supplier name
        description:
          type: string
          required: false
          description: Descripcion del proveedor.
          example: Supplier description
        nit:
          type: number
          required: true
          description: NIT del proveedor.
          example: 503
        isActive:
          type: boolean
          required: true
          description: Indica si el proveedos esta activo.
          example: true
        creatorUser:
          type: string
          required: true
          description: SUP del usuario que creo el proveedor.
          example: Supplier creator user
        editorUser:
          type: string
          required: false
          description: SUB del ultimo usuario que edito el proveedor.
          example: Supplier editor user
    Employee:
      type: object
      properties:
        uuid:
          type: string
          required: true
          description: Identificador universal unico para la tabal empleado.
          example: 2f6b7f19-e387-47f0-ac86-baf4ca1dc3c4
        firstName:
          type: string
          required: true
          description: Primer nombre del empleado.
          example: Employee first name
        middleName:
          type: string
          required: false
          description: Segundo nombre del empleado.
          example: Employee middle name
        surname:
          type: string
          required: true
          description: Primer nombre del empleado.
          example: Employee surname
        middleSurname:
          type: string
          required: false
          description: Segundo nombre del empleado.
          example: Employee middle surname
        documentType:
          type: string
          required: true
          description: Tipo de documento del empleado.
          example: Emp
        documentNumber:
          type: number
          required: true
          description: Numero de documento del empleado.
          example: 724
        birthdate:
          type: string
          required: true
          description: Fecha de nacimiento del empleado.
          example: '2024-03-17'
        isActive:
          type: boolean
          required: true
          description: Indica si el empleado esta activo.
          example: true
        creatorUser:
          type: string
          required: true
          description: SUP del usuario que creo al empleado.
          example: Employee creator user
        editorUser:
          type: string
          required: false
          description: SUB del ultimo usuario que edito al empleado.
          example: Employee editor user
  tags:
    - Supplier
    - Employee
