import {getModels} from '@db'

export const relations = () => {
  const models = getModels()
  const {Supplier, Employee, PersonalData, ContactData, EnterpriseData} = models
  const {DniType, Rh, Gender, CivilStatus, AcademicLevel, City} = models
  const {Role, Position, Eps, Afp, Ccf, Arl, RiskLevel, RiskClass, Province} = models
  const {Business, Company, Regional, Location, CompanyType, Service} = models

  Employee.belongsTo(Supplier, {foreignKey: 'supplier'})
  Supplier.hasMany(Employee, {foreignKey: 'supplier'})
  Business.hasMany(Supplier, {foreignKey: 'business'})
  Supplier.belongsTo(Business, {foreignKey: 'business'})
  Company.hasMany(Supplier, {foreignKey: 'company'})
  Supplier.belongsTo(Company, {foreignKey: 'company'})
  Regional.hasMany(Supplier, {foreignKey: 'regional'})
  Supplier.belongsTo(Regional, {foreignKey: 'regional'})
  Location.hasMany(Supplier, {foreignKey: 'location'})
  Supplier.belongsTo(Location, {foreignKey: 'location'})
  CompanyType.hasMany(Supplier, {foreignKey: 'company_type'})
  Supplier.belongsTo(CompanyType, {foreignKey: 'company_type'})
  Service.hasMany(Supplier, {foreignKey: 'service'})
  Supplier.belongsTo(Service, {foreignKey: 'service'})

  Gender.hasMany(Employee, {foreignKey: 'gender'})
  Employee.belongsTo(Gender, {foreignKey: 'gender'})
  AcademicLevel.hasMany(Employee, {foreignKey: 'academic_level'})
  Employee.belongsTo(AcademicLevel, {foreignKey: 'academic_level'})
  Position.hasMany(Employee, {foreignKey: 'position'})
  Employee.belongsTo(AcademicLevel, {foreignKey: 'position'})
  Province.hasMany(Employee, {foreignKey: 'province'})
  Employee.belongsTo(Province, {foreignKey: 'province'})
  City.hasMany(Employee, {foreignKey: 'city'})
  Employee.belongsTo(City, {foreignKey: 'city'})
  Arl.hasMany(Employee, {foreignKey: 'arl'})
  Employee.belongsTo(Arl, {foreignKey: 'arl'})
  RiskLevel.hasMany(Employee, {foreignKey: RiskLevel.tableName})
  Employee.belongsTo(RiskLevel, {foreignKey: RiskLevel.tableName})
  RiskClass.hasMany(Employee, {foreignKey: RiskClass.tableName})
  Employee.belongsTo(RiskClass, {foreignKey: RiskClass.tableName})

  Employee.hasOne(PersonalData, {foreignKey: 'uuid'})
  ContactData.belongsTo(Employee, {foreignKey: 'uuid'})
  Employee.hasOne(ContactData, {foreignKey: 'uuid'})
  EnterpriseData.belongsTo(Employee, {foreignKey: 'uuid'})
  Employee.hasOne(EnterpriseData, {foreignKey: 'uuid'})
  DniType.hasMany(Employee, {foreignKey: 'dniType'})
  Employee.belongsTo(DniType, {foreignKey: 'dniType'})
  Rh.hasMany(PersonalData, {foreignKey: 'rh'})
  PersonalData.belongsTo(Rh, {foreignKey: 'rh'})
  Gender.hasMany(PersonalData, {foreignKey: 'gender'})
  PersonalData.belongsTo(Gender, {foreignKey: 'gender'})
  CivilStatus.hasMany(PersonalData, {foreignKey: 'civil_status'})
  PersonalData.belongsTo(CivilStatus, {foreignKey: 'civil_status'})
  AcademicLevel.hasMany(PersonalData, {foreignKey: 'academic_level'})
  PersonalData.belongsTo(AcademicLevel, {foreignKey: 'academic_level'})
  Eps.hasMany(EnterpriseData, {foreignKey: 'eps'})
  EnterpriseData.belongsTo(Eps, {foreignKey: 'eps'})
  Afp.hasMany(EnterpriseData, {foreignKey: 'afp'})
  EnterpriseData.belongsTo(Afp, {foreignKey: 'afp'})
  Ccf.hasMany(EnterpriseData, {foreignKey: 'ccf'})
  EnterpriseData.belongsTo(Ccf, {foreignKey: 'ccf'})
  Role.hasMany(EnterpriseData, {foreignKey: 'role'})
  EnterpriseData.belongsTo(Role, {foreignKey: 'role'})
  Position.hasMany(EnterpriseData, {foreignKey: 'position'})
  EnterpriseData.belongsTo(Position, {foreignKey: 'position'})
  Province.hasMany(ContactData, {foreignKey: 'province'})
  ContactData.belongsTo(Province, {foreignKey: 'province'})
  City.hasMany(ContactData, {foreignKey: 'city'})
  ContactData.belongsTo(City, {foreignKey: 'city'})
  Province.hasMany(City, {foreignKey: 'province'})
  City.belongsTo(Province, {foreignKey: 'province'})
  Province.hasMany(Ccf, {foreignKey: 'province'})
  Ccf.belongsTo(Province, {foreignKey: 'province'})
}
